Fix to the Regtest network genesis block and checkpoints
stratisproject/stratisX pull request #57
Opened 2018-06-28 15:09 UTC by maciejzaleski

- Added method to check if the app is running in Regtest mode in order to return correct list of block hash checkpoints for regtest.
- Modified the parameters of the genesis block so that it returns the same blockhash as the C# StratisFullNode.
- Bumped client version to 2.0.0.5.

2018-07-02 08:20 UTC, dev0tion requested changes
Looks good @maciejzaleski.
Please also bump version in the stratis-qt.pro file.
Should we let addresses start with R so it's easy to tell networks apart?

2018-07-16 16:22 UTC, dangershony commented on src/checkpoints.cpp
> +        ( 0,      uint256("0x93925104d664314f581bc7ecb7b4bad07bcfabd1cfce4256dbd2faddcf53bd1f") )
You don't need checkpoints for regtest

2018-07-16 16:24 UTC, dangershony commented
@maciejzaleski please remove the checkoints code then we can safely commit

2018-07-16 16:35 UTC, dev0tion commented
Version bump not needed anymore as it's already done in #58

2018-10-19 09:20 UTC, closed without merging